services:
  - type: web
    name: quickpoll-backend
    env: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false

